# Tenant shared configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-defaults
  namespace: flux-system
data:
  BRANCH: main
  ISSUER: selfsigned
  GATEWAY_NS: gateway
  GATEWAY_NAME: gateway
