---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profiles.yaml
  - hostname-mappings.yaml
  - hostname-mapping-policy.yaml
  - generating-policy.yaml
  - authz-policy.yaml
