apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-{{ .Values.id }}-kustomize-controller
  namespace: flux-system
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-{{ .Values.id }}-cluster-reader
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io", "source.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses", "gateways"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-{{ .Values.id }}-namespace-admin
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "serviceaccounts", "persistentvolumeclaims", "pods", "pods/log", "pods/portforward"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["*"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "grpcroutes", "tcproutes", "tlsroutes", "udproutes", "referencegrants"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificaterequests", "issuers"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-{{ .Values.id }}-cluster-reader
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-{{ .Values.id }}-cluster-reader
subjects:
  - kind: ServiceAccount
    name: tenant-{{ .Values.id }}-kustomize-controller
    namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-{{ .Values.id }}-namespace-admin
  namespace: tenant-{{ .Values.id }}
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-{{ .Values.id }}-namespace-admin
subjects:
  - kind: ServiceAccount
    name: tenant-{{ .Values.id }}-kustomize-controller
    namespace: flux-system
