apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant-{{ .Values.id }}-source
  namespace: flux-system
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
spec:
  interval: 1m
  url: {{ .Values.repo }}
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-{{ .Values.id }}-source
  namespace: flux-system
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
spec:
  interval: 10m
  targetNamespace: tenant-{{ .Values.id }}
  sourceRef:
    kind: GitRepository
    name: tenant-{{ .Values.id }}-source
  path: ./apps
  prune: true
  wait: true
  serviceAccountName: tenant-{{ .Values.id }}-kustomize-controller
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
