---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infrastructure-tls
  namespace: cilium-system
spec:
  secretName: infrastructure-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - "*.${cluster_domain}"
