---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-tls
  namespace: cilium-system
spec:
  secretName: cluster-tls
  issuerRef:
    name: ${cluster_issuer}
    kind: ClusterIssuer
  dnsNames:
    - "*.${cluster_domain}"
