---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # API
  k8s_api_port: '6443'
  k8s_api_server: 127.0.0.1

  # CIDRs
  pod_cidr: 10.42.0.0/16
  cluster_cidr: 10.42.0.0/16
  
  # Domain
  cluster_domain: xonery.dev
  # Certificate Management
  cluster_issuer: selfsigned  # Options: selfsigned, letsencrypt-staging, letsencrypt-prod
  cluster_issuer_email: kilian.houpeurt@gmail.com
  
  # Load balancer IP pool
  lb_ip_pool_cidr_ip: 192.168.1.240
  lb_ip_pool_cidr_prefix: "30"
  # Gateway IPs (2 gateways)
  lb_public_ip: 192.168.1.240   # Cilium Gateway - Public apps
  lb_private_ip: 192.168.1.241  # Envoy Gateway - Protected apps (OIDC)
