apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:UdH9t9KWiisZRJ1/K25xf49vDwSVEe4YbRVaSiRAyZbkGZIXKWUwCJ0e8ukGMyTbFleERi/F9b405ogcsRsxQRRsz3kH57B10NJpX2YiVJoMw6mso6Kqb6VAfrtvMtghEAOgfcmqhl59DdPmw/PytWwCEPqKoN8Vcg==,iv:oWM5Cud0fwrrx+lVjQeGnjARNv1Z/W9BcUnyRHjLrPQ=,tag:LtNFp/a0yErhlK7eR0nxuw==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQzlremcyNU1RMWtlUDF4
            MmU4cnRIdjVQZHUySHZYZ1VVdklhYkNlOW1jCnphU0N4TkRhai9WYldUblpnZ29m
            ME85eFBWVU9nU25OZ3crU0RKeHpRamMKLS0tIDFReXVUalJBRGx6Qk12dkk3eXE4
            NXdOZUczV2dqWEc5ckJ5bExiMkY2TlkKifxHuFSzlmWSRycKnnMu2EFJtmh/rVev
            GFqcZEA0xbTouxropSwuudg9u1BFUWPeBR2bJtmd/qG4GNqW8h7X/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T12:37:22Z"
    mac: ENC[AES256_GCM,data:SBDXzunrR+uSuU6AnZjnVh82yCtC0HuC9DlqtToVeteMdbb3cdJb/YcaF3H0U6jQAjbSw3g26hJsW6At7XOxV/q1NNJA47UY7KvseEtk41Hg/MxBc+RNUo3HD8kSRixiP7jDBXAQCFizrxLv9grauRlBaUxk/KrDugLoGfq6ius=,iv:Etl1wzfWQA1smN8pR5OpWiZsBUy+6BwadUkQ0IqkhpA=,tag:QrXyHeZUElMFLXDcj85wdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
