apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-system
resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml
patches:
  - target:
      kind: Namespace
      name: local-path-storage
    patch: |-
      - op: replace
        path: /metadata/name
        value: storage-system
  - target:
      kind: ConfigMap
      name: local-path-config
    patch: |-
      - op: replace
        path: /data/config.json
        value: |
          {
            "nodePathMap": [
              {
                "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths": ["${local_path_storage_dir}"]
              }
            ]
          }
      - op: add
        path: /data/setup
        value: |
          #!/bin/sh
          set -eu
          mkdir -m 0777 -p "$VOL_DIR"
      - op: add
        path: /data/teardown
        value: |
          #!/bin/sh
          set -eu
          rm -rf "$VOL_DIR"
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          storageclass.kubernetes.io/is-default-class: "true"
