apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - discord.yaml
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYUE4ckV6czhUdVBBY3pz
            NnY0RWNWQXd2eDRiMllvZzdsUlVVSVRScmxFCm82bmF4bmZjV2VMSnZyb0ZkMHly
            enAxSUFObnp5SHVMcWovTXRud0NwVEEKLS0tIGEzUE1seDRWRjhVZmZQcW5vNG44
            N2RMa1FaUndnbEFOK08zM1F2M0xUbTQKb0l+mWFFyDz1XYfT7rl4gGcI9nmsDA+3
            OjaMluKbFC8sXTFeFeoZo85/R4JigwGVin9pmI5yhwZTRQwq1I++bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T17:42:59Z"
    mac: ENC[AES256_GCM,data:XO9FNbYVqzMj1lsypw0lEgo/y59BsXIp3+MQCxnL4FwxSVAKRIbRejMDQfe/o90iGNNMGWMBqT+cQd4QEv1R8xjhWDpPoUJf5ajhUxILt5QUkVK/kEXWBzFfmUJ3tILuWBTEwHH5DPqNxUp5NtVvH4SUQN8b2kSvr0miSOFxhkI=,iv:upANdBbwgWh4z+0CUduEPU/9D1o40kcvjPztzElWaOo=,tag:3iQhEBt7uR204Lj3ubYPkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
