apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
type: Opaque
stringData:
    test-key: ENC[AES256_GCM,data:ku26kABebVxmzw==,iv:U+DNU9Loxwf3sOxR7GW91v3FEcnQHEgrfuu91gG07UQ=,tag:n8nwVyE8KCdX9Er2V3E3FA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UlFFay9vYjA0M0lPY0p5
            MGVrOTBic1Rmc1A3dkQvWXRZNVJlV0g5cm40CjliRUkvbTFCVzJYYzc3Um43WXlP
            WEZMTmp6emVERGM2VGNUTDh6SXVwRUkKLS0tIG5ORXNUZDdBOHJhdlZYM0FGTHFi
            bGtPSzg2aHRUY2ZCNXp3MjZTbEFySHMKYnSGiwDTre7iV2j7hNnEjfoIWeMleXIe
            6jR7YSnmddramA9RI9O7+NDmCtj+J5n5CWwI2HrsEoyBG8PWaNafLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T11:21:30Z"
    mac: ENC[AES256_GCM,data:J/tNLYee9OEkEc0JV/zqqsBZMzPFkhAZJ8WL/jBAavleNFwERtPjHbwZx9LAj02HjRF+6KP6gkCQ04NgxKxaYL2i1gTFu8n0pGUXd1EVArsoHwyHf+ap+dime/k4+VO9BXaUzCtYih6Jj0qbSFrvBDu7Sr4SA4Symudx/WVVzNY=,iv:epHLROzP41uRuF1DrF+6zUTJc6lf05EzbwOQO/gbksg=,tag:7WqpsWh4163czbTcJ8pxLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
