apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ZsfMWOKuVK2EaJSeNoW66r8GixNSiYyfFNlC9k3Hcq1ltmjKXYUwUlJqz5+MqKAuhMO5q0lRFux2WBuzrhCHNHvkkDxVIIzhkN0snoOir4zLf6BP13vM487vWMAtEabD50ikqlm9cMNbosLyPbtB866GyWP7pNxzoQ==,iv:V336AuMiqEwjL4BkKNC8DA676XL/ZVha4Vy85kYUh30=,tag:edjNEiiEgYJQxRWi4lG+vQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSm9Fd3RLMTFrbkVVMFVz
            Vlg2aGVYYklieWk3dzFmYzFyRHUrQ2lrN3hFCmlKK2EwTmJQZDNZMXA3c2tUZnEw
            cHV4ZEhCWWR2L2RUU3Bua1d5VWVFaUEKLS0tIGFSa3NoYXB3Yzhkb2tjQmZCQlJJ
            RFdJR25ZNENKQjgrdEpGeVl6b3hiZDQKek5Jrj9VnW5zLKzWMsybwV8XnhQ6g2su
            IR7GyEUpPBT+WB8t76kDEcKwTVF32k5IdIyWBZWGn23GzOk/cC9ZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:11:07Z"
    mac: ENC[AES256_GCM,data:rN86UgmxqmcsfjSdAzAH79zDKu0SkuQChHBJEHKwkSPmseoQEDcuz+VyiypqrFRDF1818X3XFO9j+ibOgG1Uv4SkfL7iLYJUSl/a34/+7ELhAVcHoMIPbUYhu2/+8FKj/FZ37DgU2aNd3pNMSCXNkfK75LlrCE/4H1t1FdLwFH8=,iv:PzBsVVpzHdbHB/3SFOT5NKfrSU5UmEek0q5nMOZI7vs=,tag:7kEoa2Vv9rLIuuvoXsI0Ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
