apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:7v4AgIoZn3AudaVPMoRJt/R3w0q71MfPuxrAuHzAvtKckTUkOMXVZcw4k7a88pjZg+17Q42xltiEbplLjhtH2HXSQd/pGgfpWpU4e8tfFppkZ7+OP1bLonwbGdmTAOSitECDD2h8EpdeuQ4B5rXbHlGyP9Ny1rbc5A==,iv:xntabFtER0IwnpDYm3AxcYHdQn2n8lpoLZZuZzase1I=,tag:kqjSWT3HjZ+qUmPv4QIkiQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS1dlUjA3UVBJUXYrbGlt
            TVoxWXNIb0p3TW55OXFLYldkYThuSG91RzJNClRFMFAwNkxhdUdyLzhnM0pOL2JF
            VDJMb3lXWnVHUnh5SmM2WkRTVkJyTXcKLS0tIDY4UTZvYnBJREtMR2Znc1JMVWk0
            cUZXbHRVRHJGLzZzY0pCN3VhYm9NbEkKAs1TI5wj5AC6vp2h4m9BaSD2is5kwF6V
            g7NcZBrEPbIPs38wqpZs0h6I/la0F7O8zDB+pLLRHt4HDkNXYDnY7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:14:22Z"
    mac: ENC[AES256_GCM,data:bNev4qkqy51HqLMB4vrWEzMcSCo0tfEK1FGXRT6DdlMUJ4W82shgPXU07NkE60hHqMYdff0KUPKBKz5BAo96RLI0M4MEEs4172s/NkTupBTek5+ptiXzfIkkTUCJZtXFlI0ZXgpXVMLZkvwGMZhi+Fv9h+wkETBr51cIIeGZTB4=,iv:hsHlHMgjk5j+tqPN9ir+hCnvErDwTzSyGZ/ETyRivW0=,tag:1avcLSHllk5w09NUJN8K6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
