apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:R4RdERIcg3ymJAzFwy9y+Bck/ubz5Myv9cAe27qkLz5PieFHATI+8f2pZt9HwbIQH8l7tt5uinLZOpDzX0nZu0zQZxerprSD3B36rEIJ3hiUh2S2RwTfEjYq30Bho2IWu7bEvzsdnp9PRYa3TPGYiaO49e8Icoovmg==,iv:U+FFOS/eXrZ1Qb9kcAPXI6Ne7/6QnbD4hYUK2njXVs0=,tag:tRsClh3B+UyzQWsbOd7n3w==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbTRKWW1oQzhGbjYydEJ0
            TTlpbll2aTFnb0xxQzU5UEhSSk9ybFZ2ampJCmhDN0lUVmFwMkN1QVdMWE84VGxx
            OFdEZVUwQXg2RU40eit6dFU3dmRtZncKLS0tIFRpYjg1bmhwcTZOYWt6QzJLNlBE
            c3BITExXV0psY1BJMWthbnU5d0JBZmcK18NNVntF5tIz4m25jWDsNx0OnnvTBkyR
            tkRaw7eoqYdS5S8ozj0MYUJ6YuxPbs+7XoVLhJKfcj7BoNc1JIKutQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:25:42Z"
    mac: ENC[AES256_GCM,data:GjA+aV7sIw1QBXv6MYLQS25ZkSkFysXZ74NIVycUFFWxXY9Djvl8NVBkWbdx4UPGWwi2rKQwOqakH9hBBhDd2lAXMBmSaaTqy5vBRRNQi+iAOPj6hoVGIL9bQPdai8xbU3yvgbwL9rVQzBNNk0QLlZZAauBQEeIquZApeTpC5pI=,iv:88K7ECbEToQ+Ogmh6SSr3Ilxzgz3QXDSDyYqnPh3Vcc=,tag:Cc5AfLjzrsMNga8QstcWkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
