apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:jjqHxD1AfnDOCSdRZgAVdlgAiEGrDuNyFRZIzdy/J2y1k+5AaDnCDuzn9ScyDaBvKdYqtV5DOUa+3Rd0YrmB/KyJkQa+M95gsx6qe56ySyRbAkTGGpoZk3dV/o6/FFFyPbEEYSsZ+LTcgF7NSX75zcE/4A/BZrH/9A==,iv:I/6JUbyOpd671Uuc+66KJV7SQcBlik2Pf+J7tEsHdAM=,tag:zdwY2D+H4ltDzA4VucWPuQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMUNMUzJCdmNuRDNvNTYy
            SktINFd4T29iL2hadXNhM3dJL1NOd0k5b3pJCktxQ3hiakZuWG9GZnQrb1loYlFr
            OGlqMmwvRmRWc3FtNHUxTDR6SGl4TFkKLS0tIFhKM2lMT2xkdzQ3UUdIVkl0RmFy
            bzVwdmtoZkgxYXkrbVRrdms2WWRSZkEKL08gwoaOMkOLHZIYPVdnKBIIo6MDzM5n
            9rQDko51MGw0QMaqUw6oumifCeoXRiXQdviKu85JDmZRU9iXSRYxRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:59:33Z"
    mac: ENC[AES256_GCM,data:9UPlmVDfUmJ/1ywLp16FKj3K9jhEkTeEI/lNn67JeKh44T3IOKHcfTNTov3AJjj3WcsltlOIdBAhsoV5tPtFw9Askrlehbd7q9cB4/K0WZ14O4PCzKUAO1J+b7jLCarMQprlSyfxo72lLPC/ytz1qJHxxKU8z3JZYo/yZZLwmMA=,iv:7TkxB5ahVYnLAnwskXzdE5oc+7D0U2uJb/eWsy57f24=,tag:N5oy/NhigKxTSFx/MoBqMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
