apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:p0CVZ5evxHR0Wm9Tr00mHsS2BTdcqTXOVFrH2BaVM31iAn2MTJx+5uFuI5DukKYvd9r6ynHeRVkAdPmgjAxwpUTvjIkwUJ58vuoVIn4/ZshVQMiDCMR8gywvkhbD/Bbxjkr8A2a7tL+HqAs9JEgLnlx1O/K/zbJ0mQ==,iv:wiCKpkj+YDR63ED0VxAz/HEC2vAtYEOu0x40YhifmA8=,tag:FjXOqMw06YBtGZ/8P4bUqA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Rjg4NXYydjJXTGU3K1VW
            clpOc1h1SFBVLzBLbnZhUmUvc2FzbitGUVJvCjRlV1JtcHVtNDk1Z1VCQytYL3NK
            MXZjVDJFTHhOcThkaTRmakg5QVpHVW8KLS0tIGJibGhpVm51c0NuWFlTZnlkMUdu
            VXFidVZFMmVQcTdLeUMrZ2ZaVWh5c2sKC+GNjFrMVGecZfadNQeqY/Q8oa7RdTrs
            bDQ8rdicpYQzfq/LaliqPtsE3RPslGOSQdk4saN7Dn/PPCAlMYooRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:39:31Z"
    mac: ENC[AES256_GCM,data:Da5jfPiigaxVqTmoYElzOnMDbzFNZ49a7BUjczAu5LCPZWT0Uj/XZh/UwF/PuNOVGRQjeQvR3feguS78DTF2bHDfNnzCgDJgoySsifOtswvkGzQPxzPWQLqW9/eS0G9crpmTc+tL0DJ//KNUB/D6rwChW7AaLwVQcVeyeuj7dJs=,iv:Ny51PpCFrv7jj6oVQIX0EUi5h+D+J1AZvugTSUrRI0M=,tag:CKPHBfx8vmjjXkQkyg0+Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
