apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:1kRFvJupw6q7mfmDpLgYYyBf5acD6fGxQlbGzK+at11ebnOENx/CHxjCx99Sl21HzmzYAVuVMtkiSJQ0fOmwNfHoU7VpsmYkhWXRkasDB/LuvOoyaeSCbvRZIzHx96l3dKc2hi1BaRn15O7Tfi2Kv3jV1w70B7Wz7Q==,iv:4cnbrRerObf8r4hP3ayRgYFYHqVKAui2sDSqyB9+ljw=,tag:AQbRocpf2EeeRDtqhgAYEA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZDdxR3FlK1JBU010ekFV
            dUN0UFRZNm9lV2tpbzYvTU5pYXZNRXRDalJNCmEwamR4eGtyNkxFM1lYQVJMVm5j
            WTRrOWNtemNXbFlLUWxJWnU2NmV3dFEKLS0tIFZRbFM2Nnc5ak82KzlxK3IzVk8v
            c2hObWNSS0RoNXNMT21XQklYRlN4L0kKJpeU4BB1f42b8GdEHi+xKgJv93cNsptg
            uSn8DOz9lRwrNMG1TT7KliOPmhVFUMtGc9eygcUobmZbvid+RC18bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:30:52Z"
    mac: ENC[AES256_GCM,data:/2p1qLvMkJ5CGbr3el0osBr+CSKlW4tI5jBuLzNlObIDGR4FcLKUD8+PM3UP06yLBjPX/3JGTBgl9WU9qmvyG6V2BuiIrJr5FC6Hjz5LW0mgEqwpw9K3stxzLJehrG9FHKKyYgEffjK191qwC+WVUa8ifDLUaQgCrvKFfnxzui4=,iv:MX+dUyb+0MbftJEB3A+qat/CddGIz8tDiNQKS3VSm+M=,tag:0kLTBh5l4A+QEM+4mQovyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
