apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:fuwcY92mdH/MnKovkhrJvZVeUTTQcFpve5XNNmd+ObtK9cYzxNhOuhkXxWKasaPDQtnEff4tevziA4m50ug4XPV3Y37tzlMWrQhc85hd4792Qq9xY52E1gRfP5HMbnuPYQnl02X/+Hn1NXw5wrDL4P+wQc/v0t0cDg==,iv:JXm2sMN3TxguhfG1LQzWefOJ6fInBYSHyW9PuWxH1B0=,tag:ByJ7t44krVefD2IggUIeyg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VjlHSjN4ZW1tOFF2VWcy
            UGJmVXlicWZJendYNGZRbnFRZ3FXRWNReFFnCmtkU1pXb0JWRzA5N2JjR0NtdHZk
            dy9xMXZ0endiU1ZvU1lORUozeXVabWcKLS0tIElIL0ZDWjB4TDFYV3drajBlZkR1
            aGVDNnJENmtDYXp4ZWlBYzdsYkJJM1UKoOildIiQhRIh6F+m+d7yfJwg6co37VYw
            /Ypc6DOFEqex3fikutzBlWJSxjwv+DVvxpdkWcr9rVPH7kzHS9UQsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T00:21:30Z"
    mac: ENC[AES256_GCM,data:ypW/9gFF0RcwND3awU0V+K3CAVFl+CKMYpchjsaCxJ3ahFdPcelnIET4lP4ECerHhym/UQYgvMaHWSj6H+o1E5ElnhM0ynhQiD7lAq7mbTf3KiNGm0Y3tgPj2viN6LNiJBoXwg+WrMymhb75Xas830PAyMsY9+9x8F2NggZdwLc=,iv:i1xO+PxS7s+kNnS+TO/vPdI42fnqIpJKM68UIPEg++c=,tag:QTiK5cSS9ObrL3uCdmUS3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
