---
# Kratos public API (Auth UI and Self-Service)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth
  namespace: ory-system
spec:
  parentRefs:
    - name: public
      namespace: cilium-system
  hostnames:
    - "auth.${cluster_domain}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kratos-public
          port: 80
