apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - security-policy.yaml
  - callback-route.yaml
  - hydra-route.yaml
  - auth-route.yaml
  - oauth2-client.yaml
  - oauth2-client-secret.yaml
