apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - callback-route.yaml
  - hydra-backend.yaml
  - hydra-route.yaml
  - oauth2-client.yaml
  - oauth2-client-secret.yaml
  - reference-grant.yaml
