# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:f159E/yuU3K8V2qlOoGdB8o3JMRXl7xdXffkhWgXnVmi2clY,iv:8qEnFPGuMKxlo+FDjRWyxl5fGUumojmKRQWeSZdmUew=,tag:iB6PoBXQ+efVUdXwBb69eA==,type:comment]
    client_id: ENC[AES256_GCM,data:+5mjK7R5lml8kM8O/A==,iv:aUOftO3zoQJNkuHx1n/EmT6jpwv6XrS+YtxuFdI0bj0=,tag:eDqMweqMRYzuEZB+5VQU4w==,type:str]
    client_secret: ENC[AES256_GCM,data:Zik06WwS0TkDj5SOYEgkY7h7UVo4kAMGM9FwWBjO/v5MFSK8SD0zpwfMLJJa5t4F42qvrKFyoBryzL9xh6AzwQ==,iv:scpB87mKbiRpmQg/n0yirxrHrkrSfqyD7C6a+N00/V0=,tag:D1ehzkLyrL09OpJEJW3Q0w==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRkEwaDI3Szh5amYwdXE4
            NkRzUXkvZ0Y3QVdRVE8vVXo0a1dJNmdwQ2tVCjZFT25wZ28yZWUvN2hmM2hTUXlB
            djR0cjArSWJHdStoOGFySzgzbTV6Y0kKLS0tIDYwc214MVhxR2UrOXc3Z1U3Y0U1
            c3VqL3U1R1NzYUkvaTFqcWk2RXdUWmcKPYZ3a4E3HeCZs1wXEw5380lcP5qSASP/
            eIl6yidU6seYZzHxQ+bh6bqeoMSlSjdC0fc82L6/YNAROgIEsDEHXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T00:21:31Z"
    mac: ENC[AES256_GCM,data:WN+U55ama+HiTksl2dhhUvOEzBbOhQA+HCPy7NBDLLywPFhX8EOuN5X/JvNz1owpTUjiq/GLDfrm3J0on0sWZSVnNlks2Nw7L5hmtATNR7Br930sONr35W21Q6oTrlM6XMoynqqecu40gIArAJx6uS+9nGLZrTzrN6eWqmsH3lc=,iv:br7iS8jBfZoZxNssXkaPtgiqWQ916iY7k5vfSFWve1A=,tag:67mn6xo4TpaCztXSxit4Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
