# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5bf54GrzgSQ0eoOZSAFtpUR99ASaeRrk0LHR0CHXgpvq7fJ/,iv:ONfwvX6pGLgItXpcYDTpAJZwrP8ufDz7IjOLFaDwUdE=,tag:6KCXE9K7yU/n1VaBQCvhow==,type:comment]
    client_id: ENC[AES256_GCM,data:eSAkxCOOwbr6TS3Esg==,iv:fbqCuntEOP9TaEDtH2mWCJWI5VASy0bHv8iOG2NXE6U=,tag:0iJnuhtILxvz22b74PkidQ==,type:str]
    client_secret: ENC[AES256_GCM,data:m0/xr3lZkP3cQv7XPypADSZwaYzs02W/EtP49cRd+DJ195G9Ern26r9O4cC74/p105O5c1nb6ifwAowDEFT1gg==,iv:BYNudrh6ZMi5bvs86CLe0BBoLPuZ40AbMP71Fhf2CqM=,tag:o97AYIdCEH3RjQK7FSeosA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSE8xSUU3MDVlVmhaeGRj
            RWxZNnc3QXgzeE1CVHNtN2FjSW9OY0RTVFZNCnNGWUNiWWZJd3RROVlZVjRBdmVo
            OUNWam5tOUNGZ0N1Q2RySFkwWGY4UlUKLS0tICt2OXp1eEc0R1JvcGwvQ25JYkF6
            bmF2Z080U0JCc0tieGk1dmNQdHdsOWMK5f2+UexBw9n8JgCeYnZpGO2f6qS+JGmu
            HPA/IZYOGijSKxWuPGyXF/H9L6IuNjF0J6e0+qXRdwfsegZxhOS7IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:09:56Z"
    mac: ENC[AES256_GCM,data:/MDrThSRdggYZ7VhuFTvCm2np56LA9ZqH7pTeabr7OPeWwTq9nAGcrUKyHYFKt/8XfKm1NCy9ZXzLw9FqY0nI75Ai7BIsF9VpA9p7e4fVn3hGub3ir7b50wzoFM3trusj5RIcA5NgUPhFCyzDbmu6yeKAEhGFB0+xkLwPAI0HdY=,iv:VOwvEHLxTrCfMBQnpbBe4LC8hbDm986jATwbxRspsuk=,tag:BZqVVSeWft0LO+iDQRd2sA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
