# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+fKAYv5cx9PlZEXMXUrfXXJiVPMbfkUsaomLZ6kIV+QacDQe,iv:cvS1NQeEjm83r8m/rOgY4Nt5987UKysIaXw6GCV98gY=,tag:RMe/mySEhutCurf6jwYTrQ==,type:comment]
    client_id: ENC[AES256_GCM,data:rglWkbd/CdNyqpQNfQ==,iv:2seijU2K8GQrzRNunm56JkwQyrvriUZjR5VnbSa4eiE=,tag:qRNIozni2vZClGd6Q3qO6Q==,type:str]
    client_secret: ENC[AES256_GCM,data:dig7EpQPSLrmYkdPKXg+y2Z+NTuRYnE9O+gcHkTcvXOpoXg3WG6JlDo2fWjjr2XhkNrJVHqVFd11Kjrm+f9iYw==,iv:iiSblaICD5s2Zqj117zhfLhciS5/HiBZQc/nWPGkY7U=,tag:bOqtD8F/5oG/mwavmVgcBw==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMTlnc0xtWCtUNmc3OG9U
            OXF1cHBwVVJsMXYwYlhrVkZIWlJEamlSbHo0CnVrNGFHRUJZMDlKUmsrQjNveWo5
            bGtBT3BQb2UweTlDbGRWd1lWOU5tdmcKLS0tIGFpdFp4UzdBMDJLTzdnVlVkRGNy
            djVLKzZpUDVqaVJ2dWZjekxtdUlkc2sKv1XS8q6UC04HKG7Y+N12bU9htVciNAe/
            O0k3VDljpcE1KPL+hq0+JkLetn/pIpF2G/0wYF7DVMeFD+XMWQQ5eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:39:31Z"
    mac: ENC[AES256_GCM,data:rqlV3CJFGakpY1dhOeOUufm9fsf58HIJAx8s5N/z0q8cCcmRrPlN1D7lcfsY3WMmQYnjXyacyFzqbzhARinBf1cNJn0CM7tVi4xwKo6y0vwQyyKfwcat/U3MkbP1LH3ncc1wbqXuAQj51FsPJQTYTb2A62wp7rlsG8jxTnz50kY=,iv:yZMcS6ELrin0h3LrNfuG/ffqPUHW/X24urmVU4M9n7U=,tag:63LuSk8zx/WcQVYq+ZsQfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
