# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uREbbLCLYQnn/wQZx7FXRJIhYFTvzF+ims4jvsnJY1ew5nhN,iv:etWA/q0ZzmoJ2JXBBPb0iHHBUZfF28Q/8aRXKXlaB1w=,tag:kbeSHIc0HV38Ge4LuBB+1Q==,type:comment]
    client_id: ENC[AES256_GCM,data:iZTimFIKUXqgbWoI3g==,iv:byTRkRqAD+25Z80P5UZXm4Ms5aYO87SvmEtRk8o9Qso=,tag:hexqDWYSCuVxiy9u6UcwKw==,type:str]
    client_secret: ENC[AES256_GCM,data:qu65n37PJKL7vUwSwholR+OB8Q497/Qv+W7W/TSYr1QWYCA22ZroYJulMIRBjoDl1rN/Kb0P7aea8JCBW+fBfw==,iv:UfsJV3D0AZOB63/y1CZ07Dti56uC1soT+1nhtGL1vDk=,tag:pxIcxx2bVCFzlqBMIKMmNA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGxPNmRGV1lhM1ByUWlj
            ZzB3eUFXRmJRai9Sb3o3OC8yYUw4YUd6ZG44Cnptd2xocENyTmdJTnkzOVdOUnZt
            M1FjL2FQVFFjdUxUbUcxclNwRWFjZXcKLS0tIERXQjh6a3BtZ214dGQwbkZHZE9j
            SGNQWmltVFcwUWJMVEt5Z0ZLZWpNTHMKxcULNdzr8ECdCnmFLN0WCqI8XZxtjV8X
            WD+hHsgIfzAjGNumpVug/28sR47lUlIjTA/bI6RtkNIKyrBJ4Qhe2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T20:50:54Z"
    mac: ENC[AES256_GCM,data:gUWGjVIZp23uwsUuSX++G1caYz0KRdWSrSDKcWKea0mbrdWt+DTpAMTVUsSbOrmDSrGSpXOaXpGKeA8YmMlbt2tSDQr7WDOF1W1fPkylW7JgNDdq9uOR9T1ro90h/RR7TQbpuEWMzn7zrXbPLOj20gL2OlzBN1LCSSkgK5WVTzI=,iv:uBdSDI8/82/Vsmy2pniR54bPuh2fE66aSAsjoRxYMr8=,tag:ruQ0hFk7Ph0xf3ftwQuv/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
