# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:V6/cVP8WkMma8ohXp7UbRDIlXQjyzwTb/KNZNDS2FuIOdrvW,iv:CETLJ/LRUPxx//9frnQQyGpeJXE1CP61M3he0OzUSTY=,tag:9yMftwzbVBcoh2AUP6Egvg==,type:comment]
    client_id: ENC[AES256_GCM,data:XuHqcYzB/qZ8nHHAWg==,iv:h/i28cKVFTS552Vods6mb2P7g4eLRafUfVFfjeSEalM=,tag:4sjt58FbZTm5nYgljWDqtw==,type:str]
    client_secret: ENC[AES256_GCM,data:OSOaII51cZc4vZpp5zNI2yh0t/h0P7Sibpj4xa0MeC/oBds9KruHHeZrMoBu8FngDKWRIUOun8KEicWZoQv2oA==,iv:6v0H2D5oXmzZcT19kz5FzlnMk8SWFvsBjIOObfFkYe4=,tag:1fnXHAI3cpWYic6BUpt96g==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa0RoaENJNkJiU3NYanAr
            TGN3aFFjM0tUb0NaNnh6WFc1MVdzN09YY1RzCjlHTXB3dHVxWEl2ZktFUG5IMEZm
            RWRvRzQ1bEpPQlhHdlJaSUJiUHZoNTAKLS0tIFkvc0Q2RDg3alp2MWdFc3ZsWVMz
            M09GcWZaZG1MTVNNZ2srVC9oc2ZVeTAKLXBKEh00BAXiQx8fW3FlTaUEGr4KiqOU
            4397EaDrFzAlBpDUatlk3N6f/00RcSzVtTl3M9kzmNFam4obsX9xUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:11:08Z"
    mac: ENC[AES256_GCM,data:QslBm1CTKKXXttS6TWpz0ePstEJQHNqKXbZdcSShXoW5PMISDMsMT6yQSzZR2mBULBDZ5vIvLtGKiqVjQG210GmzJEGut5xBLMe8Q+0js8Tv+PqyjgrKMxfXW95y41YQi8QfDqWvBKNtsepdAHJVq48XI45JqJKuRo0G+Qlgh30=,iv:8G6wyR9rNBWcECQqPentF/lXnK33zUY9X+ZIJAEUtks=,tag:1Vm9YKU1AseSD+7pdKuoQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
