# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H3dfUmUwg7ygSDyho+fiWFV6jIxWmfV8Vy/opEPrIPodHMC/,iv:6LeURjyT71aykr/AIqRxmDS5WNPQQrHFWJEFphSYi+E=,tag:Jb8zPp2laZSds8W2ogcK0A==,type:comment]
    client_id: ENC[AES256_GCM,data:t3Pbg5njShHhfO4Flg==,iv:FVoWtyrQI/OXAK8oP+F5n/XksNmnNKgvXBbNIHM8em8=,tag:wq6yrOGGd0rV5vUJsv/PAQ==,type:str]
    client_secret: ENC[AES256_GCM,data:AULDoCbR3wiSbtrEMSebzthN4pexa/BCwS6JQkdopFvx0po4G8vRS1bc3mUUFYvFXbP3YgulDPVwEFZ8n9anoA==,iv:VgzlJ4spT8wUGPbpX1RVt/lOwc/JRoVWV2+fC7Uojb4=,tag:sOiSpKO3NuqM/EswyICm+Q==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNElyK0ZDQnE4RlVPQW1h
            cnBBc3VZU3RvSHkwYXJNaG5qeHJZb1hqOUMwCjJGY0pMYUNPQ25HcCtuNC9qZUtY
            SmlFMEp1Tmt1ZjBMNnlUVDZEZGN4VGsKLS0tIHBTYkZMem9idVBXeStJVm5QS1JL
            T2ZrSEFLTzRKUHBuZm9lcmlpUGpVbjQKnwIlQkRSf+AibNQR6FhRQO6GT4M0Riqr
            CRm0tVHu4qmatAKsEta0nc2VmbRX8zrZvcLTHzPUGjYIV56sK5Xc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:21:52Z"
    mac: ENC[AES256_GCM,data:eqgms6kPnjnjMh+fbFSjv+PaRU0z/ftH4ORkhhKJTQi0N8gG4JzL8+Y2Ac0MB5eNljKyOkd2WmR+kZgv98lqg4pecuY/U2ficgFYc+RtbvpRAYRK5O1fPV426NvB/vy0v1sNbJauxVb66ewNI8+T8KPF1Eatu/I86AZfG+mW+kY=,iv:zsz5qZZuPbaZwkgzjJgyyEb/JQSuHey+lsAgzdGtgVQ=,tag:rA+49UzggRN78JMdBCf6Jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
