# Encrypt with: sops -e -i oauth2-client-secret.yaml
# OAuth2 client credentials for Envoy Gateway OIDC
# IMPORTANT: client_secret MUST match system/controllers/network/envoy-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: envoy-gateway-client-secret
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DR8BrRZXVxl6PXGbIePf06LdtnPE8KFT8ndrzrATFb5PV848,iv:xTT018nIOr49dbUAlOZS7UkqVj1yf9trq4HWn3Byz8o=,tag:JbwDp6SK7P+Tdwcz4hzftg==,type:comment]
    client_id: ENC[AES256_GCM,data:FLFykSW0ad6dWkegeA==,iv:a3N4d92UQ4iN/K7sbPQUNP1i1ZAiSFRk8eUZs6zdbFo=,tag:sptOI1O1YZCEaS8dF7XTVQ==,type:str]
    client_secret: ENC[AES256_GCM,data:TBpOdwvmVGmjaNE8FFT293PMArflDn4fIV5Mq8WMy0NIC2S7HomBCHPsjoYBrRBk84uKEwmvj75g7mUUtI7MVQ==,iv:ccYgmD0VoxujU12/PNLdG1IOq2ms2TwRLWVzSa/9Vcc=,tag:FMrrQrFaD1py5azYar7h8g==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NW91NzBxVVBzMmxJTk5P
            cG14dlVSTnd3bGpYQzgxbVhZcnl1Zmt5OEVvCloycTFYZnlpTkZlVlkzT2N4WHpv
            L3dOenN0Rlk3RkVwRmhnRlA0SWRSYUkKLS0tIHgvTW1aSnBIc3Bub0thNkg5TDJs
            dTMyVmUyQXFnVEVSTm1NamQ0V3piTWcKw05PQA/H65U/PNRUPB6PwiRHgkQwd9cG
            vbAiGwgCXoVj+bAEDR2yqhLhgsVIs4RlQm3IVqx77T0S15oN2WFWzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:14:22Z"
    mac: ENC[AES256_GCM,data:6Ci6VByvIcGLvA9Rd9+7nl+W4oOwOEgq7iNIvbp/APtatuDcIDz2dA6X52XmluK+jAEDnHFuVIBkq+eadyJedbPHKakhut2D4p6yeKI2HeRhGhbWZ2FQDw9qmGs/wYTsqUXF7UHa4ncn3bppagbRc9a1tViWaCnqITdFTLx9D40=,iv:ofbUIQiOcuGdiWWRUV+yF/FAyOy0CGxjYVr0jqovLAE=,tag:MiVdVNceXEWB/vOQE439VQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
