apiVersion: v1
kind: Namespace
metadata:
  name: tenant-{{ .Values.id }}
  labels:
    capsule.clastix.io/tenant: {{ .Values.id }}
    tenant-display-name: {{ .Values.name }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
